param(
    [string]$TargetDir = "C:\Users\Richard\clawd\OllamaBotApp"
)

$ErrorActionPreference = "Stop"

$srcDir = Join-Path $TargetDir "src"
$logsDir = Join-Path $TargetDir "logs"
$stateDir = Join-Path $TargetDir "state"

New-Item -ItemType Directory -Force -Path $TargetDir, $srcDir, $logsDir, $stateDir | Out-Null

$packageJson = @'
{
  "name": "ollamabot-app-frame",
  "version": "0.1.0",
  "private": true,
  "type": "module",
  "scripts": {
    "start": "node src/server.js",
    "dev": "node src/server.js"
  },
  "dependencies": {
    "dotenv": "^16.4.5",
    "express": "^4.19.2",
    "p-queue": "^8.0.1"
  }
}
'@

$serverJs = @'
/**
 * OllamaBot app frame.
 * Source of truth lives in the PakMan OllamaProxy package.
 */

import { startOllamaProxyServer } from '../../PakMan/packages/OllamaProxy/server.js';

startOllamaProxyServer();
'@

$readme = @'
# OllamaBot App Frame

This is a thin app frame generated by the PakMan `OllamaBotApp` bundle.

Core logic lives in:
- `PakMan/packages/OllamaOps`
- `PakMan/packages/OllamaGuard`
- `PakMan/packages/OllamaProxy`

This frame should only carry local app configuration, logs, and state.
'@

Set-Content -Path (Join-Path $TargetDir "package.json") -Value $packageJson -Encoding UTF8
Set-Content -Path (Join-Path $srcDir "server.js") -Value $serverJs -Encoding UTF8
Set-Content -Path (Join-Path $TargetDir "README.md") -Value $readme -Encoding UTF8
Copy-Item "C:\Users\Richard\clawd\PakMan\packages\OllamaBotApp\.env.example" (Join-Path $TargetDir ".env.example") -Force

Write-Output "scaffolded:$TargetDir"

