"""
ProjMan Spec Generator - Design & Specification

Turns candidates into buildable specs via debate loop.
NOT evaluation - that's Bench's job.

Usage:
    from ProjManSpec import generate_spec, debate_loop
    
    spec = generate_spec(candidate)
"""

from typing import Dict, List, Optional
from dataclasses import dataclass, field
from datetime import datetime
import json


@dataclass
class BuildSpec:
    """Build specification for a package"""
    name: str
    purpose: str
    description: str
    category: str
    
    # Interfaces
    interfaces: Dict[str, str] = field(default_factory=dict)
    
    # Files to generate
    files: List[str] = field(default_factory=list)
    
    # Tests to generate
    tests: List[str] = field(default_factory=list)
    
    # Dependencies
    dependencies: List[str] = field(default_factory=list)
    
    # Metadata
    difficulty: str = "medium"  # low, medium, high
    estimated_time: str = "2 days"
    success_criteria: List[str] = field(default_factory=list)
    
    # Debate loop results
    debate_rounds: int = 0
    criticisms_addressed: List[str] = field(default_factory=list)
    optimizations_applied: List[str] = field(default_factory=list)
    
    generated_at: str = field(default_factory=lambda: datetime.now().isoformat())
    
    def to_dict(self) -> dict:
        return {
            "name": self.name,
            "purpose": self.purpose,
            "description": self.description,
            "category": self.category,
            "interfaces": self.interfaces,
            "files": self.files,
            "tests": self.tests,
            "dependencies": self.dependencies,
            "difficulty": self.difficulty,
            "estimated_time": self.estimated_time,
            "success_criteria": self.success_criteria,
            "debate_rounds": self.debate_rounds,
            "criticisms_addressed": self.criticisms_addressed,
            "optimizations_applied": self.optimizations_applied,
            "generated_at": self.generated_at
        }
    
    def to_ticket(self) -> dict:
        """Convert to ProjMan ticket format"""
        return {
            "title": f"Build: {self.name}",
            "description": self.description,
            "spec": self.to_dict(),
            "priority": "HIGH" if self.difficulty == "low" else "MEDIUM",
            "estimated_hours": int(self.estimated_time.split()[0]) * 8,
            "tags": ["autogenerated", self.category]
        }


def generate_spec(candidate: Dict, debate_rounds: int = 3) -> BuildSpec:
    """
    Generate build spec from candidate.
    
    Args:
        candidate: PackageCandidate dict
        debate_rounds: Number of debate loop rounds
    
    Returns:
        BuildSpec
    """
    # Initial spec
    spec = _create_initial_spec(candidate)
    
    # Debate loop
    for round in range(debate_rounds):
        # Architect proposes
        proposal = _architect_propose(spec)
        
        # Critic attacks
        criticisms = _critic_attack(proposal)
        
        # Optimizer fixes
        spec, optimizations = _optimizer_fix(proposal, criticisms)
        
        spec.debate_rounds = round + 1
        spec.criticisms_addressed.extend(criticisms)
        spec.optimizations_applied.extend(optimizations)
    
    return spec


def _create_initial_spec(candidate: Dict) -> BuildSpec:
    """Create initial spec from candidate"""
    # Generate file structure
    files = [
        f"{candidate['name']}/__init__.py",
        f"{candidate['name']}/core.py",
        f"{candidate['name']}/api.py",
    ]
    
    # Add CLI if applicable
    if "cli" in candidate.get("name", "").lower():
        files.append(f"{candidate['name']}/cli.py")
    
    # Generate tests
    tests = [
        f"tests/test_{candidate['name']}_core.py",
        f"tests/test_{candidate['name']}_api.py",
    ]
    
    # Generate interfaces from methods
    interfaces = {}
    for method in candidate.get("methods", []):
        interfaces[method] = f"{method}(self, *args) -> Any"
    
    spec = BuildSpec(
        name=candidate["name"],
        purpose=candidate.get("description", ""),
        description=candidate.get("description", ""),
        category=candidate.get("category", "unknown"),
        interfaces=interfaces,
        files=files,
        tests=tests,
        dependencies=candidate.get("dependencies", []),
        difficulty=candidate.get("complexity", "medium"),
        estimated_time=candidate.get("estimated_effort", "2 days"),
        success_criteria=[
            "All tests pass",
            "API works as specified",
            "Documentation complete"
        ]
    )
    
    return spec


def _architect_propose(spec: BuildSpec) -> BuildSpec:
    """Architect AI proposes improvements"""
    # Add more detailed interfaces
    if not spec.interfaces:
        spec.interfaces = {
            "initialize": "initialize(config: Dict) -> bool",
            "process": "process(input: Any) -> Any",
            "cleanup": "cleanup() -> None"
        }
    
    # Add more files if needed
    if len(spec.files) < 3:
        spec.files.append(f"{spec.name}/utils.py")
    
    # Add more success criteria
    if len(spec.success_criteria) < 3:
        spec.success_criteria.append("Code follows style guide")
        spec.success_criteria.append("No security vulnerabilities")
    
    return spec


def _critic_attack(spec: BuildSpec) -> List[str]:
    """Critic AI attacks the spec"""
    criticisms = []
    
    # Check for vague purpose
    if not spec.purpose or len(spec.purpose) < 10:
        criticisms.append("Purpose is too vague - be more specific")
    
    # Check for missing interfaces
    if not spec.interfaces:
        criticisms.append("No interfaces defined - what does this package do?")
    
    # Check for too many dependencies
    if len(spec.dependencies) > 5:
        criticisms.append(f"Too many dependencies ({len(spec.dependencies)}) - reduce")
    
    # Check for missing tests
    if len(spec.tests) < 2:
        criticisms.append("Not enough tests - add more coverage")
    
    # Check for vague success criteria
    if not spec.success_criteria:
        criticisms.append("No success criteria - how do we know it works?")
    
    return criticisms


def _optimizer_fix(spec: BuildSpec, criticisms: List[str]) -> tuple:
    """Optimizer AI fixes the spec"""
    optimizations = []
    
    for criticism in criticisms:
        if "vague purpose" in criticism.lower():
            spec.purpose = f"Provide {spec.category} functionality for {spec.name}"
            optimizations.append("Clarified purpose")
        
        elif "no interfaces" in criticism.lower():
            spec.interfaces = {
                "run": "run(input: Any) -> Any",
                "get_result": "get_result() -> Any"
            }
            optimizations.append("Added basic interfaces")
        
        elif "too many dependencies" in criticism.lower():
            # Keep only top 3
            spec.dependencies = spec.dependencies[:3]
            optimizations.append("Reduced dependencies")
        
        elif "not enough tests" in criticism.lower():
            spec.tests.append(f"tests/test_{spec.name}_integration.py")
            optimizations.append("Added integration test")
        
        elif "no success criteria" in criticism.lower():
            spec.success_criteria = [
                "All unit tests pass",
                "Integration tests pass",
                "API documentation complete"
            ]
            optimizations.append("Added success criteria")
    
    return spec, optimizations


def generate_ticket(spec: BuildSpec) -> Dict:
    """Generate ProjMan ticket from spec"""
    return {
        "title": f"Build: {spec.name}",
        "description": spec.description,
        "spec": spec.to_dict(),
        "priority": "HIGH" if spec.difficulty == "low" else "MEDIUM",
        "estimated_hours": int(spec.estimated_time.split()[0]) * 8,
        "tags": ["autogenerated", spec.category, f"debate_{spec.debate_rounds}_rounds"]
    }


def export_spec(spec: BuildSpec, output_file: str):
    """Export spec to JSON"""
    with open(output_file, "w") as f:
        json.dump(spec.to_dict(), f, indent=2)


def export_ticket(ticket: Dict, output_file: str):
    """Export ticket to JSON"""
    with open(output_file, "w") as f:
        json.dump(ticket, f, indent=2)


# === Main API ===

def generate_build_spec(candidate, debate_rounds=3):
    """Generate build spec"""
    return generate_spec(candidate, debate_rounds)


def create_projman_ticket(spec: BuildSpec) -> Dict:
    """Create ProjMan ticket"""
    return generate_ticket(spec)


__all__ = [
    "generate_spec",
    "generate_ticket",
    "export_spec",
    "export_ticket",
    "BuildSpec",
    "create_projman_ticket",
]
